CREATE TABLE IF NOT EXISTS expenses (
  id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  userId INT UNSIGNED NOT NULL,
  amount DECIMAL(12, 2) NOT NULL,
  category VARCHAR(80) NOT NULL,
  paymentMethod VARCHAR(50) NOT NULL,
  description VARCHAR(500) NULL,
  receiptName VARCHAR(255) NULL,
  date DATE NOT NULL,
  createdAt DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updatedAt DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  CONSTRAINT fk_expenses_user
    FOREIGN KEY (userId) REFERENCES users(id)
    ON DELETE CASCADE ON UPDATE CASCADE,
  INDEX idx_expenses_user_date (userId, date)
);
